apiVersion: apps/v1
kind: Deployment
metadata:
  name: netty-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netty-backend
  template:
    metadata:
      labels:
        app: netty-backend
    spec:
      containers:
        - name: netty-backend
          image: renukafernando/netty-http-echo-service:0.4.6-ubuntu-java8
          args:
            - "-m"
            - "1g"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "1500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
          ports:
            - containerPort: 8688
          livenessProbe:
            tcpSocket:
              port: 8688
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8688
            initialDelaySeconds: 8
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  selector:
    app: netty-backend
  ports:
    - name: http
      port: 80
      targetPort: 8688
      protocol: TCP
